// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbfhxgipapatkhlzrokb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiZmh4Z2lwYXBhdGtobHpyb2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODIyNjcsImV4cCI6MjA2NjI1ODI2N30.6kKxTEdlKAbK5L-w3fS84TtDvJ-mLxHAmwsZimyKFeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);